.catalog:
  name: master
  version: v1.2.12
  description: vote-demo-web
  uuid: master-9

vote-demo-web-app:
  scale: 1
  health_check:
    port: 8001
    interval: 10000
    strategy: none
    unhealthy_threshold: 2
    request_line: GET / HTTP/1.1
    healthy_threshold: 2
    response_timeout: 2000
