vote-demo-web:
  image: rancher/load-balancer-service
  ports:
    - 8001:8001
  links:
    - vote-demo-web-app:vote-demo-web-app

vote-demo-web-app:
  image: ferhimedamine/vote-demo-web:ferhimedamine_vote-demo-web_feature-amine_1.2.5_1_f123109c
  expose:
    - 8001
  environment:
    RANCHER_SERVICE_DISCOVERY: 'true'
    LISTEN_PORT: 8001
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
